### ISSUE TITLE
Cannot read property 'host' of undefined after setting ENV var and deleting profile via CLI

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli-cics-plugin#15] opened 2018-12-17 13:28 UTC
Steps to reproduce:
1. Create a CICS profile
2. Delete all CICS profiles via CLI
3. Perform the following:
```
user@ubuntu-base:~$ export ZOWE_OPT_USER=maskedUser
user@ubuntu-base:~$ export ZOWE_OPT_PASSWORD=maskedPass
user@ubuntu-base:~$ export ZOWE_OPT_HOST=maskedHost
user@ubuntu-base:~$ export ZOWE_OPT_PORT=1490
user@ubuntu-base:~$ bright cics get resource CICSLocalTransaction -c "PROGRAM=MARB*" --rft table --rfh --rff program tranid status --region-name maskedReg
Command Preparation Failed:
Cannot read property 'host' of undefined
```

zowe cli version: 2.0.0-next.201812071333
zowe cics plugin version: 1.1.0-next.201812131943

node version: v10.13.0
npm version: 6.4.1

**Comment by AHumanFromCA** [comment] 2018-12-17 15:00
Below is the root cause of the error message. This information confirms that it is the issue present in imperative. Further tracking on this issue will be done in zowe/imperative#43.

```
[2018/12/17 08:21:11.836] [INFO] [AbstractProfileManager.js:326] Loading profile "default" of type "cics"...
[2018/12/17 08:21:11.840] [DEBUG] [AbstractProfileManager.js:334] The default profile for type "cics" is "cicstrn1".
[2018/12/17 08:21:11.840] [DEBUG] [AbstractProfileManager.js:355] Load count for "type_name" key "cics_cicstrn1" is 1
[2018/12/17 08:21:11.840] [DEBUG] [AbstractProfileManager.js:366] Invoking the implementation to load profile "cicstrn1" of type "cics".
[2018/12/17 08:21:11.842] [DEBUG] [BasicProfileManager.js:247] Loading profile "cicstrn1" (load default: "true") of type "cics".
[2018/12/17 08:21:11.842] [DEBUG] [AbstractProfileManager.js:945] Profile "cicstrn1" of type "cics" was not found, but failNotFound=True
[2018/12/17 08:21:11.843] [ERROR] [AbstractProfileManager.js:370] Load implementation error: Cannot read property 'host' of undefined
[2018/12/17 08:21:11.843] [ERROR] [CommandProcessor.js:209] Cannot read property 'host' of undefined
```

**Comment by tjohnsonBCM** [comment] 2020-03-16 17:19
Fixed in https://github.com/zowe/imperative/pull/304

**Closed by tjohnsonBCM** 2020-03-16 17:19 UTC
Labels: bug
